name:
  max_length: 50

email:
  max_length: 255
  valid_email_regex: \A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z

password:
  min_length: 6

user:
  avatar:
    size: 80

pagy:
  items: 10

micropost:
  content:
    max_length: 140

image:
  max_width: 200
  max_height: 200

digit_2: 2

digit_5: 5
